### PR TITLE
Merge back changes from mlo

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by st3fan** [comment]
@unho Can you please explain the rationale for these changes? What does this fix or improve? We need a little more context please.

**Comment by unho** [comment]
@st3fan I think the changes are not difficult to follow. First one is about skipping locales that don't require processing since they were excluded. Second one is some minor code cleanups to align with Python coding guidelines.

**Comment by flodolo** [comment]
For a bit more background: mlo is https://mozilla.locamotion.org (Pootle), one of the tools where localization happens. 

In the past I asked them to clean up the files before commit, so their diffs don't look huge and confusing in GitHub, and they ended up using the same scripts we use.

I'd be fine with these changes, I only wonder if you have pointers to documentation suggesting to use that form of `print`, because otherwise I'd prefer consistency with the rest of the scripts.

**Comment by unho** [comment]
@flodolo `print` was a reserved word in Python 2 and older, but in newer Python 3 it is just a function and thus the parentheses are necessary. If you use `print()` it works both on Python 2 and 3, so I suggest you change everywhere to use `print()`. Perhaps it is better explained in some of the following links:
- https://docs.python.org/3/whatsnew/3.0.html#print-is-a-function
- https://www.codecademy.com/en/forum_questions/52f295c8631fe9ccd000079b#answer-52f29f209c4e9d4a39000245
- http://spartanideas.msu.edu/2014/06/01/the-key-differences-between-python-2-7-x-and-python-3-x-with-examples/#The-print-function

**Comment by flodolo** [comment]
Looks like this one was forgotten.

Looking back at the code, I think it makes sense to say something when you skip a locale that was explicitly requested when calling the script, at least you can fix the origin of the call, e.g. 

``` python
print("Locale %s is in the list of excluded locales" % locale)
```

**Comment by unho** [comment]
@flodolo Sure. Feel free to land whichever changes you like.

**Pull request closed without merging**
