### PR TITLE
Bug 1325176 - Improve Pass XLIFF filename as parameter to update-xliff.py

### PR DESCRIPTION
**Pull request by flodolo**
* Pass XLIFF file name as parameter
* Don't die when parsing broken XML files
* Add mapping for es-ES

### CODE REVIEW

**Review by st3fan — APPROVED** [review]
Looks good to me. Let's land it. We will probably do a final 6.0 RC build this week, so that is a good moment we can test this out.

**Comment by st3fan** [comment]
Oh wait, are these changes to support Focus? I think that is great. But I also think we may want to pull out the L10N scripts from this repo then and move them to a new project that is just about L10N support?

Also, @thebnich will have to think about wether we actually want to do the exact same thing we did for Firefox L10N. Not 100% sure if that is the right approach for Focus.

**Comment by flodolo** [comment]
> Oh wait, are these changes to support Focus?

Yes, in the sense that it lets me run the same script for Firefox and Focus, since I can pass the name of the file.

If we want to reuse this for Focus, I consider it a prerequisite. Even if we don't, it's still useful for me locally.

Also note that you need this script to export new strings to other languages, not just for build.

**Comment by flodolo** [comment]
One more thing: I realized that the existing script dies on a broken XML file, instead of moving on to the remaining locales.

**Comment by thebnich** [comment]
To follow up on our IRC discussion this morning, I've been testing `xcodebuild` import/export on [this branch](https://github.com/thebnich/focus/tree/l10n). The commands I'm using:

```
./xliff-export.py ../Blockzilla.xcodeproj xliff
(manually update XLIFF)
./xliff-import.py ../Blockzilla.xcodeproj xliff
```

I tried this with **fr**, and you can see the results in the latest commit in that branch. It mostly works, with one big missing part: the Xcode project doesn't get updated.

I think we can do the same thing we're doing in `firefox-ios-build-tools`, which is to use the `XcodeProject` API to manually update the `pbxproj`. If we do that in `xliff-import.py` after the `lproj` generation, I *think* we'd need only those two scripts, so we wouldn't need everything else in `firefox-ios-build-tools`.

That said, it seems like the l10n structure will be the same regardless of the scripts we're using, so we can just use the scripts we have now so that we can do localization ASAP. I can work on the above in parallel if that sounds good to @flodolo and @st3fan.

**Comment by flodolo** [comment]
If we can simplify the import process, I'm all for that. I don't think we should change the export process though, because it ensures reasonable results for the l10n repository.

If you want to test the import process, I suggest to try with Italian, which is already fully localized.
https://github.com/mozilla-l10n/focusios-l10n/blob/master/it/focus-ios.xliff

**Pull request merged**
