### PR TITLE
Add mandatory strings to cleanup, don't die on parsing errors

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
@st3fan 
I've rebased this PR, can you take a look.

As for failing on parsing errors, I don't think that should happen on the update, but on one of the files used to import strings.

**Comment by flodolo** [comment]
@st3fan 
What should we do with this?

**Comment by st3fan** [comment]
@flodolo  Lets decide after we ship Firefox 11.0 - I am a little nervous about changes the day before we do our final build.

I think if we do a `continue` instead of a hard `sys.exit(1)` that should be configured with a `--continue-on-errors` flag. Because this is useful for development builds but a production build should be red in our CI if one of the locales fails to import. What do you think?

**Comment by flodolo** [comment]
> Lets decide after we ship Firefox 11.0 - I am a little nervous about changes the day before we do our final build.

Sure, I was mostly interested in understanding if we want to do this. I honestly forgot it was here.

**Comment by flodolo** [comment]
Added a second commit:
* The `continue`  on the reference file in update didn't make a lot of sense. Without en-US, the script would die anyway a few lines later.
* Added a `--ignore-errors` to both bash and python script to ignore errors in localized files.

This definitely needs testing on the iOS side.

**Review by st3fan — APPROVED** [review]
This looks good. Let's land this and if there is additional work we can patch it up as we go.

**Pull request merged**
